# Generated by Django 3.2.1 on 2024-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
