# Generated by Django 3.2.1 on 2024-03-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_remove_product_return_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='view_count',
        ),
    ]
