# Generated by Django 3.2.1 on 2024-07-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0023_auto_20240725_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro'), ('NGN', 'Naira'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], max_length=3),
        ),
    ]
